### ISSUE TITLE
Reconsider default values

### ISSUE THREAD

**Issue by dokempf** [ssciwr/cookiecutter-cpp-project#40]
There is two things that I dislike about the current defaults:
* The Yes/No options flip quite wildly which is a bit of a disturbing user experience
* Since the introduction of `sonarcloud` the combination of default configurations is invalid.

**Comment by lkeegan** [comment]
It would also be nice if invalid combinations of options resulted in an earlier error message, or even better if an alternative valid option was offered to the user, rather than them filling in all the options and only getting an error message at the end of the process.  (I don't know if this would fit easily into the cookiecutter framework or not)

**Comment by dokempf** [comment]
I am currently catching invalid configurations as early as cookiecutter allows, which is after the configuration prompts, but before the actual project generation. The only other option that I have is changing the default values of some configuration values based on previous configuration values, e.g. https://github.com/ssciwr/cookiecutter-cpp-project/blob/main/cookiecutter.json#L14 I am not sure this is a good thing to do.
